"""Initial PostGIS schema

Revision ID: 5b6ea5d04ccc
Revises: 
Create Date: 2026-09-15 03:48:48.245612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2



# revision identifiers, used by Alembic.
revision: str = '5b6ea5d04ccc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roads',
    sa.Column('road_id', sa.Text(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('road_type', sa.Text(), nullable=True),
    sa.Column('road_name', sa.Text(), nullable=True),
    sa.Column('road_length_km', sa.Numeric(), nullable=True),
    sa.Column('risk_score', sa.Numeric(), nullable=False),
    sa.Column('predicted_disruption', sa.Boolean(), nullable=False),
    sa.Column('elevation_m', sa.Numeric(), nullable=True),
    sa.Column('slope_deg', sa.Numeric(), nullable=True),
    sa.Column('historical_landslide_count', sa.Integer(), nullable=True),
    sa.Column('nearest_landslide_distance_km', sa.Numeric(), nullable=True),
    sa.Column('rainfall_24h_mm', sa.Numeric(), nullable=True),
    sa.Column('rainfall_3d_mm', sa.Numeric(), nullable=True),
    sa.Column('rainfall_7d_mm', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open','blocked')", name='check_road_status'),
    sa.PrimaryKeyConstraint('road_id')
    )

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user','admin')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('road_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('road_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.road_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('road_id', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['road_id'], ['roads.road_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('submission_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_history')
    op.drop_index('idx_submissions_location', table_name='submissions', postgresql_using='gist')
    op.drop_table('submissions')
    op.drop_table('road_status_history')
    op.drop_table('users')
    op.drop_index('idx_roads_geometry', table_name='roads', postgresql_using='gist')
    op.drop_table('roads')
    # ### end Alembic commands ###
